### PR TITLE
fix source address not being set in non REUSEPORT dialer

### PR DESCRIPTION
**Pull request by Kubuxu**
Part of https://github.com/ipfs/go-ipfs/issues/4088

### CODE REVIEW

**Comment by Kubuxu** [comment]
It might still not be enough

**Comment by Stebalien** [comment]
Could you rebase off of master? I fixed the minimum go version for travis (green check marks are pretty).

---

Regardless, LGTM. Even if it's not enough, it's still strictly more correct. Is there an easy way to test this?

**Comment by Kubuxu** [comment]
There unfortunately isn't a good way to test for it. I will think more about it as I would really like to have test for it once I figure out how to make it not dial other addresses.

**Comment by Stebalien** [comment]
Tested locally.

**Pull request merged**
