### PR TITLE
Update go-reuseport, fix context passing, publish 1.0.2

### PR DESCRIPTION
**Pull request by Kubuxu**
This version of go-reuseport contains:

* performance and resource improvement via reduction of locked system threads from one per dial operation to one per whole process.
* fix for go-reuseport closing randomly file descriptors which might in past lead to random unexpected behaviors.

### CODE REVIEW

**Comment by whyrusleeping** [comment]
blocked on https://github.com/jbenet/go-reuseport/pull/17#pullrequestreview-2214686

**Comment by Kubuxu** [comment]
Fixed go-vet in https://github.com/libp2p/go-tcp-transport/pull/3

**Comment by whyrusleeping** [comment]
merged #3, want to rebase?

**Comment by Kubuxu** [comment]
No as it would mean that published hash doesn't match, I can republish it but it would be 4th time I do that.

I can create merge commit.

**Comment by whyrusleeping** [comment]
@Kubuxu okay, do the tests pass locally? lol

**Comment by Kubuxu** [comment]
It does: http://gateway.ipfs.io/ipfs/Qmast4eYX6mCtQsHQgK8ZtS5T2YbWeQ1pwUr99fNy2kbFk/screencap.2016-10-03T20:19:55Z.png

**Comment by whyrusleeping** [comment]
Alright, LGTM

**Pull request merged**
